name: Release macOS binary

on:
  push:
    tags:
      - "v*.*.*"  # e.g. v1.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --release

      - name: Prepare binary for release
        run: |
          mkdir -p dist
          cp target/release/feedline dist/feedline-macos

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/feedline-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
