name: Release macOS/linux binaries

on:
  push:
    tags:
      - "v*.*.*"  # e.g. v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rustlang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release
